### ISSUE TITLE
[Fix] backend 컨테이너 이미지 저장 위치 마운트

### ISSUE THREAD

**Issue by Jack-R-lantern** [404-DriverNotFound/ft_transcendence-b#20]
## 문제점
백엔드 컨테이너가 새롭게 실행될때마다 이미지를 못찾는 상황.

## 예상되는(제대로 된) 동작
백엔드 컨테이너를 새롭게 실행해도 이미지를 정상적으로 가져옴.

## 해결 방법 (optional)
docker-compose 구성에서 이미지가 저장되는 위치를 마운트 시켜서 해결.

## 버그 재현 방법 (버그를 발생시키는 방법)
1. docker-compose로 컨테이너를 구동 / 이미지를 업로드.
2. docker-compose로 컨테이너를 재구동.
3. 이미지를 정상적으로 못찾는 상황 발생

**Comment by Jack-R-lantern** [comment]
기존 docker-compose의 백엔드 구성
```
  backend:
    build:
      context: ./backend-b
      dockerfile: Dockerfile
    restart: always
```

변경 후 docker-compose의 백엔드 구성
```
  backend:
    build:
      context: ./backend-b
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend-b/files:/app/files
```
